export const TEETER_TOTTER_WIDTH = 10
export const FIGURE_TYPES = ['circle', 'triangle', 'rectangle']
export const FIGURE_COUNT = FIGURE_TYPES.length
export const MAX_WEIGHT = 10
export const MIN_WEIGHT = 1
export const MAX_BENDING = 30
export const MAX_SIDES_DIFFERENCE = 20
export const FALLING_FIGURES_COUNT = 2
export const FALL_DELTA_PX = 10
export const FALL_TIMEOUT = 200
export const FALL_TIMEOUT_DECREASING = 10
